### ISSUE TITLE
Test ReportViewer is not working

### ISSUE THREAD

**Issue by mathew-weaver** [software-architects/AzureWebsitesGetHdcTest#1]
I just tried the sample app hosted here:
http://azurewebsitesgethdctest.azurewebsites.net/

I clicked the Test ReportViewer button, and it generates the GDI "Parameter is not valid" exception:

Server Error in '/' Application.

Parameter is not valid.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.ArgumentException: Parameter is not valid.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[ArgumentException: Parameter is not valid.]
   System.Drawing.Graphics.GetHdc() +1138213

**Comment by rstropek** [comment]
Hi Mathew!

Demonstrating this behavior was the point of this sample (see https://github.com/software-architects/AzureWebsitesGetHdcTest).

Regards,
Rainer.
